### ISSUE TITLE
Data Factory ingestion pipeline not triggered after finops-hub deployment

### ISSUE THREAD

**Issue by helderpinto** [microsoft/cloud-hubs#174]
## 🐛 Problem
After successfully deploying finops-hub from [Azure Quickstart templates](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.costmanagement/finops-hub) and configuring ACM cost exports, the Data Factory ingestion pipeline is not triggered, despite ACM cost exports CSV blobs being generated daily in the `msexports` container. I tried to restart the ADF trigger, but the issue persists.

## 👣 Repro steps

1. Follow the [finops-hub deployment instructions](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.costmanagement/finops-hub#how-to-use-this-template)
2. Wait 24-48 hours
3. Check the `ingestion` container in the finops-hub Storage Account
4. Verify the container is empty, despite the `msexports` container being populated with a new CSV every day

## 🤔 Expected

I expect the ingestion container to have a new blob every day as a result of the ingestion pipeline trigger.

## 📷 Screenshots

Event grid subscription created by ADF trigger:

![image](https://github.com/microsoft/cloud-hubs/assets/10661605/404404a0-88b9-4654-88a3-b4fae04789cc)

Evidence of CSVs being exported to the `msexports` container:

![image](https://github.com/microsoft/cloud-hubs/assets/10661605/6c64bcaa-d735-47bf-9939-7f33c0c7f295)

Evidence of Advanced Filter Evaluation metrics in the Event Grid Subscription (notice the 0 delivered events):

![image](https://github.com/microsoft/cloud-hubs/assets/10661605/de94bf58-7812-4d69-9187-d9bf4220fb40)

**Comment by MSBrett** [comment]
The checkbox to partition the data needs to be enabled on the export for the trigger to fire.

**Comment by helderpinto** [comment]
Thanks, @MSBrett . It did the trick. I didn't find this documented. I am going to add a documentation change in PR #179

**Comment by flanakin** [comment]
@all-contributors please add helderpinto for bug reports

**Comment by peter-mogaka** [comment]
Hi @flanakin ,

I'm facing almost similar issues. The only the ETL ingestion pipeline keeps failing. No file is then added to the ingestion container. I have added sample error messages, and it looks like it's having a prob converting the csv file. The FileAdded is triggered successfully. 

I'm using latest finops hub, configured partiniong, exporting using "Cost and usage details (FOCUS) - Preview"
![Skjermbilde 2024-07-08 153150](https://github.com/microsoft/finops-toolkit/assets/78694283/d7ec8792-de1c-4c3c-a41d-9dbe8c0b834d)
![Skjermbilde 2024-07-08 153157](https://github.com/microsoft/finops-toolkit/assets/78694283/5947bcc7-abeb-414c-ac9d-326b3ace62f1)
![Skjermbilde 2024-07-08 153245](https://github.com/microsoft/finops-toolkit/assets/78694283/74ff2aed-b51c-455d-9db8-ced24f504945)

**Comment by helderpinto** [comment]
@peter-mogaka, which FOCUS dataset version are you using? `1.0-preview` or `1.0`? See below a typical working configuration. 

Also, are you a MCA or EA customer? 

![image](https://github.com/microsoft/finops-toolkit/assets/10661605/15e629b0-2e11-47fc-be7e-85531097c8da)

**Comment by peter-mogaka** [comment]
Hi @helderpinto, 

I tried with the 1.0-preview(v1) and ingestion works/populated. 
We're EA but moving to MCA within a year. Does EA/MCA have an effect on the hub?

**Comment by helderpinto** [comment]
Hi, @peter-mogaka. 

Good to know that switching to `1.0-preview(v1)` solved the problem.

Regarding EA vs. MCA, there should be no difference besides the export scope/directory path configuration and some small MCA [limitations](https://microsoft.github.io/finops-toolkit/power-bi/commitment-discounts#savings) that hopefully will be fixed within a year. I just asked so that we had as much details as possible about the issue.
